EXCLUDED_API = [
    "/docz",
    "/docs",
    "/redocz",
    "/openapi.json",
    # App status & health (probes, toggle, reset)
    "/app-health-status",
    "/app-maintenance-status",
    "/app-data-ingestion-status",
    "/toggle-app-maintenance-status",
    "/toggle-app-data-ingestion-status",
    "/reset-app-data-ingestion-status",
    # "/products/actions/download/xlsx/details-report",
    # "/stores/actions/download/xlsx/details-report",
    # "/products-stores/actions/download/xlsx/details-report",
    # Need to remove the routers which are not getting used
    "/products/actions/download/xlsx/details-report-upload",
    "/stores/actions/download/xlsx/details-report-upload",
    "/products-stores/actions/download/xlsx/details-report-upload",
    "/products/actions/upload/xlsx/details",
    "/optimization/post-processing",
    "/strategies/generate-forecast",
    "/strategies/products-and-stores-v2",
    "/strategies/fetch-grid-data",
    "/strategies/pre-process",
    "/optimization/process_async",
    "/notification-pre-process",
    "/strategies/refresh-strategy",
    "/strategies/clone-strategy",
    "/strategies/pre-process-rules",
    "/workers/products_stores",
    "/workers/process_rules",
    "/workers/process_forecast",
    "/coordinator",
    "/workers/fetch-grid-data",
    "/workers/cache_grid_data",
    "/worker/products-stores",
    "/worker/process-rules",
    "/worker/process-forecast",
    "/coordinator/pre-processing-coordinator",
    "/worker/cache-strategy-grid-data",
    "/worker/process-recommendation-insertion",
    "/worker/update-strategy-master",
    "/coordinator/post-processing-coordinator",
    "/worker/refresh-dashboard-metrics",
    "/worker/process-targets",
    "/workers/process_targets",
    # Notification WebSocket endpoints
    "/notifications/ws",
    "/notifications/system/websocket-test",
    "/notifications/system/health",
    "/notifications/system/stats",
    "/competitor/actions/download/xlsx/details-report-upload",
    "/strategies/actions/download/xlsx/details-report-upload",
    "/notifications/trigger-websocket",
    # Bulk Update Cloud Run Endpoints
    "/",
    "/orchestrator/",
    "/orchestrator/health",
    "/orchestrator/bulk-updates",
    "/orchestrator/table-completed",
    "/processor/",
    "/processor/health",
    "/processor/process-batch",
    "/daily-data-refresh",
    "/baseline-metrics-refresh",
]
